version: '3'

services:

  runner:
    image: gitlab/gitlab-runner
    restart: always
    volumes:
      - /root/gitlab-runner/config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/repositories-aufs:/var/lib/docker/repositories-aufs
      - /var/lib/docker/graph:/var/lib/docker/graph
      - /var/lib/docker/aufs:/var/lib/docker/aufs
