# Generated by Django 2.2.1 on 2019-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_take_web_notification',
            field=models.BooleanField(default=True, verbose_name='takes web notifications'),
        ),
    ]
