# Generated by Django 2.2.1 on 2019-05-13 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='faces', verbose_name='image')),
                ('face_link', models.URLField(verbose_name='face link')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='datetime')),
                ('confidence', models.FloatField(verbose_name='confidence')),
                ('meta', models.TextField(blank=True, verbose_name='meta')),
                ('camera', models.UUIDField(verbose_name='camera id')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
            },
        ),
    ]
