# Generated by Django 2.2.1 on 2019-05-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0003_eventnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventnotification',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='is new'),
        ),
    ]
