# Generated by Django 2.2.1 on 2019-05-15 10:40

from django.db import migrations


def round_percent(apps, schema_editor):
    Event = apps.get_model('faces', 'Event')
    for event in Event.objects.all():
        event.confidence = round(event.confidence*100.0)
        event.save()


def reverse_percent(apps, schema_editor):
    Event = apps.get_model('faces', 'Event')
    for event in Event.objects.all():
        event.confidence = event.confidence/100.0
        event.save()


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0004_eventnotification_is_new'),
    ]

    operations = [
        migrations.RunPython(round_percent, reverse_percent),
    ]
