# Generated by Django 2.2.1 on 2019-05-15 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0005_auto_20190515_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='confidence',
            field=models.PositiveSmallIntegerField(verbose_name='confidence'),
        ),
    ]
