# Generated by Django 2.2.1 on 2019-05-24 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0007_auto_20190524_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='is read by at least one user'),
        ),
        migrations.AlterField(
            model_name='event',
            name='age',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='возраст'),
        ),
        migrations.AlterField(
            model_name='event',
            name='gender',
            field=models.CharField(blank=True, max_length=10, verbose_name='пол'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='is_new',
            field=models.BooleanField(default=True, verbose_name='новый'),
        ),
        migrations.AlterField(
            model_name='eventnotification',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='прочитано'),
        ),
    ]
