# Generated by Django 2.2.1 on 2019-05-24 12:08

from django.db import migrations


def forwards_func(apps, schema_editor):
    """Update events is_read status according to notification."""
    Event = apps.get_model("faces", "Event")
    Event.objects.filter(
        eventnotification__is_read=True
    ).distinct().update(
        is_read=True
    )


def reverse_func(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0008_auto_20190524_1506'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
