# Generated by Django 2.2.1 on 2019-05-29 07:29

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('faces', '0009_auto_20190524_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='full_img',
            field=sorl.thumbnail.fields.ImageField(null=True, upload_to='faces', verbose_name='full image'),
        ),
        migrations.AddField(
            model_name='event',
            name='rect_bottom',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='rect_left',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='rect_right',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='rect_top',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='img',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='faces', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='прочитано минимум одним пользователем'),
        ),
    ]
